### ISSUE TITLE
Почему бы не использовать bem-core dist?

### ISSUE THREAD

**Issue by sbmaxx** [DimitryDushkin/bem-light-example#1]
https://ru.bem.info/forum/469/

**Comment by DimitryDushkin** [comment]
1. `npm dist` в `bem-core` собирает всё, что увидит (перенастроить нельзя)
2.  Мне хотелось бы тут иметь полноценную BEM-структуру проекта с минимум заморочек с enb. Всё остальное, что можно сделать с помощью gulp, например, вынести из enb.

Всё это для того, чтобы основные крутости BEM stack были бы доступы всем (типа уровней переопределения, филигранного инклуда блоков и пр.), даже тем, кто не хочет тратить время на познание enb.

Чуть подробнее про эту истории тут — https://ru.bem.info/forum/530/

**Comment by sbmaxx** [comment]
:ok_hand:
