### ISSUE TITLE
Make скрипт и компиляция scss

### ISSUE THREAD

**Issue by indra-uolles** [DimitryDushkin/bem-light-example#5]
Можно ли переделать make скрипт таким образом, чтобы при компиляции scss в css выводилось более детальное описание ошибок? Типа упал при обработке такого-то файла.

**Comment by DimitryDushkin** [comment]
Это вопрос к enb-sass. Посмотрю, что можно сделать.

**Comment by DimitryDushkin** [comment]
В целом ситуацию улучшит этот пулл https://github.com/enb-make/enb-sass/pull/5

**Comment by DimitryDushkin** [comment]
Перешли на stylus =)
